//
// Milkyway Hierarchical Verilog Dump:
// Generated on 04/18/2017 at 11:38:30
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :three_eight_decoder_LIB
// Cell Name    :three_eight_decoder
// Hierarchy delimiter:'/'
// Write Command : write_verilog three_eight_decoder.pnr.v
//


module three_eight_decoder (s , k , right );
output [7:0] s ;
input  [2:0] k ;
input  right ;



INVX2 U6 (.A ( right ) , .Y ( n4 ) ) ;
INVX2 U5 (.A ( k[0] ) , .Y ( n3 ) ) ;
INVX2 U4 (.A ( k[1] ) , .Y ( n2 ) ) ;
INVX2 U3 (.A ( k[2] ) , .Y ( n1 ) ) ;
FILL xofiller_FILL_1 () ;
FILL xofiller_FILL_2 () ;
FILL xofiller_FILL_3 () ;
FILL xofiller_FILL_4 () ;
OAI22X1 U14 (.A ( n9 ) , .B ( n11 ) , .C ( n10 ) , .D ( n12 ) , .Y ( s[2] ) ) ;
OAI22X1 U13 (.A ( n5 ) , .B ( n11 ) , .C ( n7 ) , .D ( n12 ) , .Y ( s[3] ) ) ;
NAND2X1 U12 (.A ( n1 ) , .B ( n4 ) , .Y ( n8 ) ) ;
NAND2X1 U11 (.A ( right ) , .B ( k[2] ) , .Y ( n6 ) ) ;
OAI22X1 U10 (.A ( n8 ) , .B ( n5 ) , .C ( n7 ) , .D ( n6 ) , .Y ( s[4] ) ) ;
OAI22X1 U9 (.A ( n8 ) , .B ( n9 ) , .C ( n6 ) , .D ( n10 ) , .Y ( s[5] ) ) ;
OAI22X1 U8 (.A ( n6 ) , .B ( n9 ) , .C ( n8 ) , .D ( n10 ) , .Y ( s[6] ) ) ;
OAI22X1 U7 (.A ( n5 ) , .B ( n6 ) , .C ( n7 ) , .D ( n8 ) , .Y ( s[7] ) ) ;
NAND2X1 U22 (.A ( k[1] ) , .B ( k[0] ) , .Y ( n5 ) ) ;
NAND2X1 U21 (.A ( k[2] ) , .B ( n4 ) , .Y ( n12 ) ) ;
NAND2X1 U20 (.A ( n3 ) , .B ( n2 ) , .Y ( n7 ) ) ;
NAND2X1 U19 (.A ( right ) , .B ( n1 ) , .Y ( n11 ) ) ;
OAI22X1 U18 (.A ( n5 ) , .B ( n12 ) , .C ( n7 ) , .D ( n11 ) , .Y ( s[0] ) ) ;
NAND2X1 U17 (.A ( k[1] ) , .B ( n3 ) , .Y ( n9 ) ) ;
NAND2X1 U16 (.A ( k[0] ) , .B ( n2 ) , .Y ( n10 ) ) ;
OAI22X1 U15 (.A ( n9 ) , .B ( n12 ) , .C ( n10 ) , .D ( n11 ) , .Y ( s[1] ) ) ;
FILL xofiller_FILL_5 () ;
FILL xofiller_FILL_6 () ;
FILL xofiller_FILL_7 () ;
FILL xofiller_FILL_8 () ;
FILL xofiller_FILL_9 () ;
FILL xofiller_FILL_10 () ;
FILL xofiller_FILL_11 () ;
FILL xofiller_FILL_12 () ;
FILL xofiller_FILL_13 () ;
FILL xofiller_FILL_14 () ;
FILL xofiller_FILL_15 () ;
FILL xofiller_FILL_16 () ;
FILL xofiller_FILL_17 () ;
FILL xofiller_FILL_18 () ;
FILL xofiller_FILL_19 () ;
FILL xofiller_FILL_20 () ;
FILL xofiller_FILL_21 () ;
FILL xofiller_FILL_22 () ;
FILL xofiller_FILL_23 () ;
FILL xofiller_FILL_24 () ;
FILL xofiller_FILL_25 () ;
FILL xofiller_FILL_26 () ;
FILL xofiller_FILL_27 () ;
FILL xofiller_FILL_28 () ;
FILL xofiller_FILL_29 () ;
FILL xofiller_FILL_30 () ;
FILL xofiller_FILL_31 () ;
FILL xofiller_FILL_32 () ;
FILL xofiller_FILL_33 () ;
FILL xofiller_FILL_34 () ;
FILL xofiller_FILL_35 () ;
FILL xofiller_FILL_36 () ;
FILL xofiller_FILL_37 () ;
FILL xofiller_FILL_38 () ;
FILL xofiller_FILL_39 () ;
FILL xofiller_FILL_40 () ;
FILL xofiller_FILL_41 () ;
FILL xofiller_FILL_42 () ;
FILL xofiller_FILL_43 () ;
FILL xofiller_FILL_44 () ;
FILL xofiller_FILL_45 () ;
FILL xofiller_FILL_46 () ;
FILL xofiller_FILL_47 () ;
FILL xofiller_FILL_48 () ;
FILL xofiller_FILL_49 () ;
FILL xofiller_FILL_50 () ;
FILL xofiller_FILL_51 () ;
FILL xofiller_FILL_52 () ;
FILL xofiller_FILL_53 () ;
FILL xofiller_FILL_54 () ;
FILL xofiller_FILL_55 () ;
FILL xofiller_FILL_56 () ;
FILL xofiller_FILL_57 () ;
FILL xofiller_FILL_58 () ;
FILL xofiller_FILL_59 () ;
FILL xofiller_FILL_60 () ;
FILL xofiller_FILL_61 () ;
FILL xofiller_FILL_62 () ;
endmodule


