//
// Milkyway Hierarchical Verilog Dump:
// Generated on 03/31/2017 at 17:23:23
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :mips_fsm_LIB
// Cell Name    :mips_fsm
// Hierarchy delimiter:'/'
// Write Command : write_verilog mips_fsm.pnr.v
//


module mips_fsm (op , alusrcb , pcsrc , reset , clk , irwrite , aluop , 
    regdst , regwrite , brnch , pcwrite , iord , memtoreg , alusrca , 
    memwrite );
input  [5:0] op ;
output [1:0] alusrcb ;
output [1:0] pcsrc ;
input  reset ;
input  clk ;
output [3:0] irwrite ;
output [1:0] aluop ;
output regdst ;
output regwrite ;
output brnch ;
output pcwrite ;
output iord ;
output memtoreg ;
output alusrca ;
output memwrite ;


wire [3:0] state ;

assign aluop[0] = brnch ;
assign pcsrc[0] = brnch ;
INVX2 U5 (.A ( n19 ) , .Y ( pcsrc[1] ) ) ;
AND2X2 U4 (.A ( n17 ) , .B ( op[5] ) , .Y ( n47 ) ) ;
AND2X2 U3 (.A ( n44 ) , .B ( n5 ) , .Y ( N21 ) ) ;
DFFPOSX1 state_reg_1_ (.Q ( state[1] ) , .CLK ( clk ) , .D ( N22 ) ) ;
DFFPOSX1 state_reg_2_ (.Q ( state[2] ) , .CLK ( clk ) , .D ( N23 ) ) ;
DFFPOSX1 state_reg_3_ (.Q ( state[3] ) , .CLK ( clk ) , .D ( N24 ) ) ;
DFFPOSX1 state_reg_0_ (.Q ( state[0] ) , .CLK ( clk ) , .D ( N21 ) ) ;
INVX2 U13 (.A ( state[1] ) , .Y ( n9 ) ) ;
INVX2 U12 (.A ( n25 ) , .Y ( n8 ) ) ;
INVX2 U11 (.A ( n21 ) , .Y ( n7 ) ) ;
INVX2 U10 (.A ( state[2] ) , .Y ( n6 ) ) ;
INVX2 U9 (.A ( state[3] ) , .Y ( n5 ) ) ;
INVX2 U8 (.A ( irwrite[3] ) , .Y ( n4 ) ) ;
INVX2 U7 (.A ( alusrcb[1] ) , .Y ( n3 ) ) ;
INVX2 U6 (.A ( memwrite ) , .Y ( n2 ) ) ;
INVX2 U21 (.A ( op[0] ) , .Y ( n17 ) ) ;
INVX2 U20 (.A ( op[1] ) , .Y ( n16 ) ) ;
INVX2 U19 (.A ( op[2] ) , .Y ( n15 ) ) ;
INVX2 U18 (.A ( op[3] ) , .Y ( n14 ) ) ;
INVX2 U17 (.A ( n33 ) , .Y ( n13 ) ) ;
INVX2 U16 (.A ( reset ) , .Y ( n12 ) ) ;
INVX2 U15 (.A ( n41 ) , .Y ( n11 ) ) ;
INVX2 U14 (.A ( state[0] ) , .Y ( n10 ) ) ;
NOR2X1 U29 (.A ( n23 ) , .B ( n24 ) , .Y ( memtoreg ) ) ;
NAND2X1 U28 (.A ( state[0] ) , .B ( n9 ) , .Y ( n22 ) ) ;
NOR2X1 U27 (.A ( n20 ) , .B ( n22 ) , .Y ( irwrite[1] ) ) ;
NOR2X1 U26 (.A ( n8 ) , .B ( n20 ) , .Y ( irwrite[2] ) ) ;
NAND3X1 U25 (.A ( state[3] ) , .B ( state[2] ) , .C ( n21 ) , .Y ( n19 ) ) ;
NAND2X1 U24 (.A ( n19 ) , .B ( n20 ) , .Y ( pcwrite ) ) ;
NOR2X1 U23 (.A ( n18 ) , .B ( n8 ) , .Y ( regdst ) ) ;
OR2X1 U22 (.A ( regdst ) , .B ( memtoreg ) , .Y ( regwrite ) ) ;
OAI21X1 U37 (.A ( n3 ) , .B ( n26 ) , .C ( n27 ) , .Y ( N24 ) ) ;
NOR2X1 U36 (.A ( state[0] ) , .B ( state[1] ) , .Y ( n21 ) ) ;
NOR2X1 U35 (.A ( n7 ) , .B ( n20 ) , .Y ( irwrite[0] ) ) ;
AOI21X1 U34 (.A ( n3 ) , .B ( n18 ) , .C ( n10 ) , .Y ( alusrca ) ) ;
OAI21X1 U33 (.A ( state[3] ) , .B ( n7 ) , .C ( n20 ) , .Y ( alusrcb[0] ) ) ;
NOR2X1 U32 (.A ( n18 ) , .B ( n24 ) , .Y ( brnch ) ) ;
NOR2X1 U31 (.A ( n7 ) , .B ( n18 ) , .Y ( memwrite ) ) ;
OAI21X1 U30 (.A ( n23 ) , .B ( n8 ) , .C ( n2 ) , .Y ( iord ) ) ;
OAI21X1 U45 (.A ( n33 ) , .B ( n34 ) , .C ( n4 ) , .Y ( n32 ) ) ;
NAND2X1 U44 (.A ( n32 ) , .B ( n12 ) , .Y ( n31 ) ) ;
OAI21X1 U43 (.A ( n30 ) , .B ( n23 ) , .C ( n31 ) , .Y ( N23 ) ) ;
OAI21X1 U42 (.A ( n16 ) , .B ( n15 ) , .C ( n11 ) , .Y ( n26 ) ) ;
NAND2X1 U41 (.A ( state[3] ) , .B ( n6 ) , .Y ( n18 ) ) ;
NAND3X1 U40 (.A ( n13 ) , .B ( alusrcb[1] ) , .C ( op[3] ) , .Y ( n29 ) ) ;
OAI21X1 U39 (.A ( state[1] ) , .B ( n18 ) , .C ( n29 ) , .Y ( n28 ) ) ;
NAND3X1 U38 (.A ( n28 ) , .B ( n12 ) , .C ( state[0] ) , .Y ( n27 ) ) ;
OAI21X1 U53 (.A ( reset ) , .B ( n38 ) , .C ( n39 ) , .Y ( N22 ) ) ;
NOR2X1 U52 (.A ( op[2] ) , .B ( n16 ) , .Y ( n35 ) ) ;
AOI22X1 U51 (.A ( n35 ) , .B ( n11 ) , .C ( n36 ) , .D ( n37 ) , .Y ( n30 ) ) ;
NOR2X1 U50 (.A ( n23 ) , .B ( state[1] ) , .Y ( alusrcb[1] ) ) ;
NAND2X1 U49 (.A ( alusrcb[1] ) , .B ( n14 ) , .Y ( n34 ) ) ;
NAND2X1 U48 (.A ( n6 ) , .B ( n5 ) , .Y ( n20 ) ) ;
NAND2X1 U47 (.A ( state[1] ) , .B ( state[0] ) , .Y ( n24 ) ) ;
NOR2X1 U46 (.A ( n20 ) , .B ( n24 ) , .Y ( irwrite[3] ) ) ;
OAI21X1 U61 (.A ( op[1] ) , .B ( n41 ) , .C ( n45 ) , .Y ( n44 ) ) ;
NAND3X1 U60 (.A ( n14 ) , .B ( n5 ) , .C ( n13 ) , .Y ( n43 ) ) ;
AOI21X1 U59 (.A ( state[2] ) , .B ( n43 ) , .C ( state[1] ) , .Y ( n42 ) ) ;
NOR2X1 U58 (.A ( n9 ) , .B ( state[0] ) , .Y ( n25 ) ) ;
AOI22X1 U57 (.A ( n42 ) , .B ( state[0] ) , .C ( n25 ) , .D ( n5 ) , .Y ( n38 ) ) ;
NAND2X1 U56 (.A ( state[2] ) , .B ( n5 ) , .Y ( n23 ) ) ;
NOR2X1 U55 (.A ( op[1] ) , .B ( n23 ) , .Y ( n40 ) ) ;
NAND3X1 U54 (.A ( n11 ) , .B ( op[2] ) , .C ( n40 ) , .Y ( n39 ) ) ;
NOR2X1 U69 (.A ( reset ) , .B ( state[0] ) , .Y ( n36 ) ) ;
OR2X1 U68 (.A ( op[4] ) , .B ( op[5] ) , .Y ( n49 ) ) ;
NOR2X1 U67 (.A ( op[3] ) , .B ( n49 ) , .Y ( n48 ) ) ;
NAND3X1 U66 (.A ( n36 ) , .B ( n17 ) , .C ( n48 ) , .Y ( n41 ) ) ;
NOR2X1 U65 (.A ( op[4] ) , .B ( op[2] ) , .Y ( n46 ) ) ;
NAND3X1 U64 (.A ( n46 ) , .B ( n16 ) , .C ( n47 ) , .Y ( n33 ) ) ;
NAND2X1 U63 (.A ( n9 ) , .B ( n33 ) , .Y ( n37 ) ) ;
OAI21X1 U62 (.A ( n6 ) , .B ( n37 ) , .C ( n36 ) , .Y ( n45 ) ) ;
assign aluop[1] = 1'b0;
endmodule


